stubrunner:
  cloud.stubbed.discovery.enabled: false
  repositoryRoot: http://repo.spring.io/milestone
server.port: ${PORT:8083}
spring:
  cloud.stream.defaultBinder: rabbit
  application:
    name: stubrunner